apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: my-udagram-feed-api
  labels:
    app: my-udagram-feed-api
spec:
  # number of replicated pods
  replicas: 2
  selector:
    matchLabels:
      app: my-udagram-feed-api
  template:
    metadata:
      labels:
        app: my-udagram-feed-api
    spec:
      containers:
      # docker image name
      - name: udagram-feed-api
        image: abdelrahmansherif/udacity-udagram-microservice-feed
        env:
        - name: POSTGRES_USERNAME
          value: -----
        - name: POSTGRES_PASSWORD
          value: "-----"
        - name: POSTGRES_HOST
          value: -----
        - name: POSTGRES_DB
          value: -----
        - name: AWS_BUCKET
          value: -----
        - name: AWS_REGION
          value: -----
        - name: AWS_PROFILE
          value: -----
        - name: JWT_SECRET
          value: -----
        - name: URL
          value: -----
        ports:
        - containerPort: 8081
