apiVersion: v1
kind: Service
metadata:
  name: my-udagram-feed-api-svc
  labels:
    run: my-udagram-feed-api-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: my-udagram-feed-api
